IF OBJECT_ID('SPS_ABCS_USU','P') IS NOT NULL DROP PROCEDURE SPS_ABCS_USU
GO
CREATE PROCEDURE DBO.SPS_ABCS_USU
(
	@ACCION      VARCHAR(1) = 'S',
	@USUARIOID   VARCHAR(100) = NULL,
	@CLAVE	     VARCHAR(100) = NULL,
	@NOMBRE		 VARCHAR(100)=NULL,
	@GRUPOID	 VARCHAR(100)=NULL,
	@ACTIVO		 SMALLINT = NULL,
	@EMAIL		 VARCHAR(100)=NULL,
	-- @USUARIOIDOLD VARCHAR(100)=NULL,
	@SEDEID		  VARCHAR(100)=NULL
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @SQLString AS nvarchar(MAX)
	
	IF @ACCION = 'A'
	BEGIN
		INSERT INTO USU(USUARIOID,CLAVE,NOMBRE,GRUPOID,ACTIVO,EMAIL,SEDEID)
		SELECT @USUARIOID,ENCRYPTBYPASSPHRASE(DBO.FNS_VALORVARIABLE('KEYCIFRAR'),LTRIM(RTRIM(@CLAVE))),@NOMBRE,@GRUPOID,@ACTIVO,@EMAIL,@SEDEID
		-- WHERE NOT EXISTS(SELECT * FROM USU WHERE USUARIOID=@USUARIOID)
		WHERE NOT EXISTS(SELECT * FROM USU WHERE EMAIL=@EMAIL OR (USUARIOID=@USUARIOID AND SEDEID=@SEDEID))
	END 
	IF @ACCION = 'B'
	BEGIN
		DELETE FROM USU WHERE USUARIOID = @USUARIOID
	END
	IF @ACCION = 'C'
	BEGIN
		UPDATE USU SET 
			CLAVE=CASE WHEN @CLAVE IS NULL THEN CLAVE ELSE ENCRYPTBYPASSPHRASE(DBO.FNS_VALORVARIABLE('KEYCIFRAR'),LTRIM(RTRIM(@CLAVE))) END,
			NOMBRE = CASE WHEN @NOMBRE IS NULL THEN NOMBRE ELSE @NOMBRE END,
			GRUPOID = CASE WHEN @GRUPOID IS NULL THEN GRUPOID ELSE @GRUPOID END,
			ACTIVO = CASE WHEN @ACTIVO IS NULL THEN ACTIVO ELSE CASE WHEN @ACTIVO<=0 THEN 0 ELSE 1 END END,
			EMAIL = CASE WHEN @EMAIL IS NULL THEN EMAIL ELSE @EMAIL END,
			SEDEID = CASE WHEN @SEDEID IS NULL THEN SEDEID ELSE @SEDEID END
		WHERE USUARIOID=@USUARIOID
	END
	IF @ACCION = 'S'
	BEGIN

		SET @SQLString='SELECT USUARIOID,NOMBRE,USU.GRUPOID,USGRU.DescripcionGrupo AS GRUPO,USU.ACTIVO,EMAIL '
		SET @SQLString=@SQLString+',EMP.RAZONSOCIAL AS EMPRESA, USU.SEDEID,SED.RAZONSOCIAL AS SEDE '
		SET @SQLString=@SQLString+'FROM USU '
		SET @SQLString=@SQLString+'LEFT JOIN USGRU ON USGRU.GRUPOID=USU.GRUPOID '
		SET @SQLString=@SQLString+'LEFT JOIN SED ON SED.SEDEID=USU.SEDEID '
		SET @SQLString=@SQLString+'LEFT JOIN EMP ON EMP.EMPRESAID=SED.EMPRESAID '
		SET @SQLString=@SQLString+'WHERE 1=1 '
		IF ISNULL(@USUARIOID,'')<>'' SET @SQLString=@SQLString+'AND USUARIOID = '''+@USUARIOID+''' '
		IF ISNULL(@CLAVE,'')<>'' SET @SQLString=@SQLString+'AND CONVERT(VARCHAR(300), DECRYPTBYPASSPHRASE(DBO.FNS_VALORVARIABLE(''KEYCIFRAR''),CLAVE)) = '''+@CLAVE+''''
		IF ISNULL(@GRUPOID,'')<>'' SET @SQLString=@SQLString+'AND USU.GRUPOID = '''+@GRUPOID+''' '
		IF ISNULL(@EMAIL,'')<>'' SET @SQLString=@SQLString+'AND EMAIL = '''+@EMAIL+''' '
		IF ISNULL(@SEDEID,'')<>'' SET @SQLString=@SQLString+'AND USU.SEDEID = '''+@SEDEID+''' '

		--PRINT @SQLSTRING
		EXECUTE sp_executesql @SQLString
	 
	
			--AND	CLAVE = CASE WHEN ISNULL(@CLAVE,'')='' THEN CLAVE ELSE ENCRYPTBYPASSPHRASE(DBO.FNS_VALORVARIABLE('KEYCIFRAR'),LTRIM(RTRIM(@CLAVE))) END
		END
END
GO
EXEC DBO.SPS_ABCS_USU @ACCION='A',@USUARIOID='EZERPA',@CLAVE='enclave', @NOMBRE='EBERT ZERPA',@GRUPOID='ADM',@ACTIVO=1,@EMAIL='ebert15@hotmail.com',@SEDEID='PPAL'
--EXEC DBO.SPS_ABCS_USU @ACCION='S',@USUARIOID='EZERPA',@CLAVE='enclave', @SEDEID='PPAL'
EXEC DBO.SPS_ABCS_USU




