IF OBJECT_ID('SPS_ABCS_SED','P') IS NOT NULL DROP PROCEDURE SPS_ABCS_SED
GO
CREATE PROCEDURE DBO.SPS_ABCS_SED
(
	@ACCION			VARCHAR(1) = 'S',
	@SEDEID			VARCHAR(100) = '',
	@RAZONSOCIAL	VARCHAR(500) = '',
	@DOMICILIO		VARCHAR(500) = '',
	@TELEFONO		VARCHAR(20)  = '',
	@EMPRESAID		VARCHAR(100) = '',
	@ACTIVA			SMALLINT = -1
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @SQLString AS nvarchar(MAX)
	
	IF @ACCION = 'A'
	BEGIN
		INSERT INTO SED(SEDEID,RAZONSOCIAL,DOMICILIO,TELEFONO,EMPRESAID,ACTIVA)
		SELECT @SEDEID,@RAZONSOCIAL,@DOMICILIO,@TELEFONO,@EMPRESAID,@ACTIVA
		WHERE NOT EXISTS(SELECT * FROM SED WHERE SEDEID=@SEDEID)
	END 
	IF @ACCION = 'B'
	BEGIN
		DELETE FROM SED WHERE SEDEID = @SEDEID
		AND SEDEID NOT IN (SELECT DISTINCT SEDEID FROM USU)
	END
	IF @ACCION = 'C'
	BEGIN
		UPDATE SED SET 
			RAZONSOCIAL=@RAZONSOCIAL,
			DOMICILIO=@DOMICILIO,
			TELEFONO=@TELEFONO,
			ACTIVA=@ACTIVA,
			EMPRESAID=@EMPRESAID
		WHERE SEDEID=@SEDEID
	END
	IF @ACCION = 'S'
	BEGIN

		SET @SQLString='SELECT SED.*, EMP.RAZONSOCIAL AS EMPRESA '
		SET @SQLString=@SQLString+'FROM SED LEFT JOIN EMP ON EMP.EMPRESAID=SED.EMPRESAID '
		SET @SQLString=@SQLString+'WHERE 1=1 '
		IF ISNULL(@SEDEID,'')<>'' SET @SQLString=@SQLString+'AND SEDEID = '''+@SEDEID+''' '
		IF ISNULL(@RAZONSOCIAL,'')<>'' SET @SQLString=@SQLString+'AND RAZONSOCIAL = '''+@RAZONSOCIAL+''' '
		IF ISNULL(@DOMICILIO,'')<>'' SET @SQLString=@SQLString+'AND DOMICILIO = '''+@DOMICILIO+''' '
		IF ISNULL(@TELEFONO,'')<>'' SET @SQLString=@SQLString+'AND TELEFONO = '''+@TELEFONO+''' '
		IF ISNULL(@EMPRESAID,'')<>'' SET @SQLString=@SQLString+'AND EMPRESAID = '''+@EMPRESAID+''' '
		IF ISNULL(@ACTIVA,-1) >= 0 SET @SQLString=@SQLString+'AND ACTIVA = '+CAST(@ACTIVA AS VARCHAR)

		--PRINT @SQLSTRING
		EXECUTE sp_executesql @SQLString
	 
	
			--AND	CLAVE = CASE WHEN ISNULL(@CLAVE,'')='' THEN CLAVE ELSE ENCRYPTBYPASSPHRASE(DBO.FNS_VALORVARIABLE('KEYCIFRAR'),LTRIM(RTRIM(@CLAVE))) END
		END
END
GO
--EXEC DBO.SPS_ABCS_SED --'A','PPAL','PRINCIPAL','AVENIDA 28 25 21, BOGOTA, BOGOTA','(1)3402277','900074352',1
EXEC DBO.SPS_ABCS_SED @SEDEID='ppal'




