IF OBJECT_ID('SPS_EJECUTAR_CONSULTA_PARAMETRO','P') IS NOT NULL DROP PROCEDURE SPS_EJECUTAR_CONSULTA_PARAMETRO
GO
CREATE PROCEDURE DBO.SPS_EJECUTAR_CONSULTA_PARAMETRO
(
	@ReporteID			INT				--Identificador del Reporte
	,@ParametroID		INT				--Identificador del Parámetro
	--,@TotalPaginas		INT = 0 OUTPUT	--Retorno de cantidad de páginas
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @SQLString AS nvarchar(MAX)
	SELECT @SQLString = QUERY FROM REPP WHERE REPORTEID=@ReporteID AND PARAMETROID=@ParametroID
	--EXECUTE sp_executesql @SQLString
	--PRINT @SQLString
	EXEC(@SQLString)
END
GO
EXEC DBO.SPS_EJECUTAR_CONSULTA_PARAMETRO @ReporteID=1, @ParametroID=1


--SELECT * FROM REPU WHERE 1=1 AND SEDEID = 'PPAL' AND USUARIOID = 'EZERPA' AND REPORTEID = 'CF45685A-6697-447A-B1EA-F10BA955B4079SAS' 

