IF OBJECT_ID('SPS_ABCS_REPP','P') IS NOT NULL DROP PROCEDURE SPS_ABCS_REPP
GO
CREATE PROCEDURE DBO.SPS_ABCS_REPP
(
	@ACCION			VARCHAR(1) = 'S',
	@PARAMETROID	BIGINT = -1,
	@NOMBRE			VARCHAR(100) = '',
	@TIPO			VARCHAR(20) = '',
	@VALOR			VARCHAR(MAX)='',
	--@UTILIZAQUERY	SMALLINT = -1,
	@QUERY			VARCHAR(MAX)='',
	@REPORTEID		BIGINT = -1
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @SQLString AS nvarchar(MAX)
	
	IF @ACCION = 'A'
	BEGIN
		INSERT INTO REPP(NOMBRE,TIPO,VALOR,UTILIZAQUERY,QUERY,REPORTEID)
		SELECT @NOMBRE,CASE WHEN ISNULL(@TIPO,'')='' THEN 'ALFANUMERICO' ELSE @TIPO END, @VALOR,CASE WHEN ISNULL(@QUERY,'')='' THEN 0 ELSE 1 END,@QUERY,@REPORTEID
		WHERE NOT EXISTS(SELECT * FROM REPP WHERE REPORTEID=@REPORTEID AND NOMBRE=@NOMBRE)
	END 
	IF @ACCION = 'B'
	BEGIN
		DELETE FROM REPP WHERE PARAMETROID=@PARAMETROID AND REPORTEID=CASE WHEN ISNULL(@REPORTEID,'')<>'' THEN @REPORTEID ELSE REPORTEID END
	END
	IF @ACCION = 'C'
	BEGIN
		UPDATE REPP SET 
			NOMBRE=CASE WHEN ISNULL(@NOMBRE,'')='' THEN NOMBRE ELSE @NOMBRE END,
			TIPO=CASE WHEN ISNULL(@TIPO,'')='' THEN TIPO ELSE @TIPO END,
			VALOR=@VALOR,--CASE WHEN ISNULL(@VALOR,'')='' THEN VALOR ELSE @VALOR END,
			UTILIZAQUERY=CASE WHEN ISNULL(@QUERY,'')='' THEN CASE WHEN ISNULL(QUERY,'')='' THEN 0 ELSE 1 END ELSE 1 END,
			QUERY=CASE WHEN ISNULL(@QUERY,'')='' THEN QUERY ELSE @QUERY END,
			REPORTEID=CASE WHEN ISNULL(@REPORTEID,-1)>0 THEN @REPORTEID ELSE REPORTEID END
		WHERE PARAMETROID=@PARAMETROID 
		AND REPORTEID = CASE WHEN ISNULL(@REPORTEID,-1)>0 THEN @REPORTEID ELSE REPORTEID END
	END
	IF @ACCION = 'S'
	BEGIN
		SET @SQLString='SELECT * '
		SET @SQLString=@SQLString+'FROM REPP '
		SET @SQLString=@SQLString+'WHERE 1=1 '
		IF ISNULL(@NOMBRE,'')<>'' SET @SQLString=@SQLString+'AND NOMBRE = '''+@NOMBRE+''' '
		IF ISNULL(@PARAMETROID,-1) > 0 SET @SQLString=@SQLString+'AND PARAMETROID = '+CAST(@PARAMETROID AS VARCHAR)
		IF ISNULL(@REPORTEID,-1) > 0 SET @SQLString=@SQLString+'AND REPORTEID = '+CAST(@REPORTEID AS VARCHAR)
		SET @SQLString=@SQLString+'ORDER BY NOMBRE '
		--PRINT @SQLSTRING
		EXECUTE sp_executesql @SQLString
	END
END
GO
EXEC DBO.SPS_ABCS_REPP @ACCION='A', @REPORTEID='1', @NOMBRE='@NumeroIdentificacion', @QUERY='SELECT DISTINCT NumeroIdentificacion FROM AFI WITH(NOLOCK)'
EXEC DBO.SPS_ABCS_REPP @ACCION='C', @PARAMETROID=2, @TIPO='ALFANUMERICO', @QUERY='SELECT DISTINCT NumeroIdentificacion FROM AFI WITH(NOLOCK)'

EXEC DBO.SPS_ABCS_REPP @REPORTEID=1 --@USUARIOID='EZERPA', @SEDEID='PPAL'--@SEDEID='ppal'





