IF OBJECT_ID('SPS_ABCS_EMP','P') IS NOT NULL DROP PROCEDURE SPS_ABCS_EMP
GO
CREATE PROCEDURE DBO.SPS_ABCS_EMP
(
	@ACCION			VARCHAR(1) = 'S',
	@EMPRESAID		VARCHAR(100) = '',
	@RAZONSOCIAL	VARCHAR(500) = '',
	@DOMICILIO		VARCHAR(500) = '',
	@TELEFONO		VARCHAR(20)  = '',
	@NIT			VARCHAR(20)  = '',
	@ACTIVA			SMALLINT = -1
	--@EMPRESAID VARCHAR(100)=''
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @SQLString AS nvarchar(MAX)
	
	IF @ACCION = 'A'
	BEGIN
		INSERT INTO EMP(EMPRESAID,RAZONSOCIAL,DOMICILIO,TELEFONO,NIT,ACTIVA)
		SELECT @EMPRESAID,@RAZONSOCIAL,@DOMICILIO,@TELEFONO,@NIT,@ACTIVA
		WHERE NOT EXISTS(SELECT * FROM EMP WHERE EMPRESAID=@EMPRESAID)
	END 
	IF @ACCION = 'B'
	BEGIN
		DELETE FROM EMP WHERE EMPRESAID = @EMPRESAID
		AND EMPRESAID NOT IN (SELECT DISTINCT EMPRESAID FROM SED)
	END
	IF @ACCION = 'C'
	BEGIN
		UPDATE EMP SET 
			RAZONSOCIAL=@RAZONSOCIAL,
			DOMICILIO=@DOMICILIO,
			TELEFONO=@TELEFONO,
			ACTIVA=@ACTIVA,
			NIT=@NIT
		WHERE EMPRESAID=@EMPRESAID
	END
	IF @ACCION = 'S'
	BEGIN

		SET @SQLString='SELECT * '
		SET @SQLString=@SQLString+'FROM EMP '
		SET @SQLString=@SQLString+'WHERE 1=1 '
		IF ISNULL(@EMPRESAID,'')<>'' SET @SQLString=@SQLString+'AND EMPRESAID = '''+@EMPRESAID+''' '
		IF ISNULL(@RAZONSOCIAL,'')<>'' SET @SQLString=@SQLString+'AND RAZONSOCIAL = '''+@RAZONSOCIAL+''' '
		IF ISNULL(@DOMICILIO,'')<>'' SET @SQLString=@SQLString+'AND DOMICILIO = '''+@DOMICILIO+''' '
		IF ISNULL(@TELEFONO,'')<>'' SET @SQLString=@SQLString+'AND TELEFONO = '''+@TELEFONO+''' '
		IF ISNULL(@NIT,'')<>'' SET @SQLString=@SQLString+'AND NIT = '''+@NIT+''' '
		IF ISNULL(@ACTIVA,-1) >= 0 SET @SQLString=@SQLString+'AND ACTIVA = '+CAST(@ACTIVA AS VARCHAR)

		--PRINT @SQLSTRING
		EXECUTE sp_executesql @SQLString
	 
	
			--AND	CLAVE = CASE WHEN ISNULL(@CLAVE,'')='' THEN CLAVE ELSE ENCRYPTBYPASSPHRASE(DBO.FNS_VALORVARIABLE('KEYCIFRAR'),LTRIM(RTRIM(@CLAVE))) END
		END
END
GO
--EXEC DBO.SPS_ABCS_EMP --'A','900074352', 'RENDIMOS LTDA', 'AVENIDA 28 25 21, BOGOTA, BOGOTA','(1)3402277','900074352',1




