IF OBJECT_ID('SPS_ABCS_ARCH','P') IS NOT NULL DROP PROCEDURE SPS_ABCS_ARCH
GO
CREATE PROCEDURE DBO.SPS_ABCS_ARCH
(
	@ACCION			        VARCHAR(1) = 'S',
    @ARCHIVOID              VARCHAR(20) = '',
	@NOMBRE                 VARCHAR(MAX) = '',
	@ARCHIVO                VARCHAR(MAX) = NULL
)
WITH ENCRYPTION
AS
BEGIN
	DECLARE @SQLString AS nvarchar(MAX)
	
	IF @ACCION = 'A'
	BEGIN
        SET @ARCHIVOID = CASE WHEN ISNULL(@ARCHIVOID,'')='' THEN REPLACE(RIGHT(NEWID(),20),'-','') ELSE @ARCHIVOID END

	    INSERT INTO dbo.ARCH(
            ARCHIVOID
            ,NOMBRE
            ,ARCHIVO
        )
		SELECT @ARCHIVOID
            ,@NOMBRE
            ,CONVERT(VARBINARY(MAX),@ARCHIVO)

        --SELECT * FROM ARCH WHERE ARCHIVOID=@ARCHIVOID
        SET @ACCION='S'
	END 
	IF @ACCION = 'B'
	BEGIN
		DELETE FROM ARCH WHERE ARCHIVOID = @ARCHIVOID
	END
	IF @ACCION = 'C'
	BEGIN
        SET @ACCION='S'
        
	END
	IF @ACCION = 'S'
	BEGIN

    --    SET @SQLString='SELECT ARCH.* '
	-- 	SET @SQLString=@SQLString+'FROM ARCH '
	-- 	SET @SQLString=@SQLString+'WHERE 1=1 '

    --     IF ISNULL(@ARCHIVOID,'')<>'' SET @SQLString=@SQLString+'AND ARCHIVOID = '''+@ARCHIVOID+''' '

		-- PRINT @SQLSTRING
	-- 	EXECUTE sp_executesql @SQLString
        SELECT ARCHIVOID, NOMBRE, ARCHIVO FROM ARCH WHERE ARCHIVOID=CASE WHEN ISNULL(@ARCHIVOID,'')='' THEN ARCHIVOID ELSE @ARCHIVOID END
	 
	
	END
END
GO
EXEC DBO.SPS_ABCS_ARCH 




