/*Usuarios del sistema*/
IF OBJECT_ID('AFI','U') IS NOT NULL DROP TABLE AFI
GO

CREATE TABLE [dbo].[AFI](
	[TipoId] [varchar](2) NOT NULL,
	[NumeroIdentificacion] [varchar](16) NOT NULL,
	[PrimerNombre] [varchar](50) NOT NULL,
	[SegundoNombre] [varchar](50) NULL,
	[PrimerApellido] [varchar](50) NOT NULL,
	[SegundoApellido] [varchar](50) NULL,
	[Sexo] [varchar](1) NOT NULL,
	[FechaNacimiento] [varchar](10) NOT NULL,
	[CiudadNacimiento] [varchar](5) NOT NULL,
	[EstadoCivil] [varchar](1) NOT NULL,
	[NivelEscolaridad] [varchar](2) NULL,
	[Celular] [varchar](11) NULL,
	[ActividadEconomica] [varchar](6) NOT NULL,
	[CodigoAFP] [varchar](10) NULL,
	[DireccionResidencia] [varchar](200) NOT NULL,
	[TelefonoResidencia] [varchar](9) NULL,
	[CiudadResidencia] [varchar](5) NOT NULL,
	[ZonaResidencia] [varchar](1) NOT NULL,
	[TipoUsuario] [varchar](2) NULL,
	[Parentesco] [varchar](2) NULL,
	[FechaSGSSS] [varchar](10) NULL,
	[EPSAnterior] [varchar](10) NULL,
	[FechaEPSAnterior] [varchar](10) NULL,
	[DiasCotizacion] [varchar](4) NULL,
	[IPSMedica] [varchar](10) NULL,
	[IPSMixta] [varchar](10) NULL,
	[IPSOdontologica] [varchar](10) NULL,
	[IsDiscapacitado] [varchar](1) NOT NULL,
	[TipoDiscapacidad] [varchar](1) NULL,
	[GradoDiscapacidad] [varchar](1) NULL,
	[PorcentajeDiscapacidad] [varchar](3) NULL,
	[FechaIniIncapacidad] [varchar](10) NULL,
	[FechaFinIncapacidad] [varchar](10) NULL,
	[IsEstudiante] [varchar](1) NOT NULL,
	[FechaIniEstudiante] [varchar](10) NULL,
	[FechaFinEstudiante] [varchar](10) NULL,
	[CodigoInstitucionEst] [varchar](200) NULL,
	[BarrioResidencial] [varchar](15) NULL,
	[Pregunta1] [varchar](1) NULL,
	[Pregunta2] [varchar](1) NULL,
	[Email] [varchar](150) NULL,
	[IsRecienNacido] [varchar](1) NOT NULL,
	[IsNietoAmparado] [varchar](1) NOT NULL,
	[TipoIdNietoAmparo] [varchar](2) NULL,
	[IdentificacionNietoAmparo] [varchar](16) NULL,
	[Estado] [bit] NOT NULL,
	[usuario_crea] [varchar](15) NOT NULL,
	[fecha_creacion] [datetime] NOT NULL,
	[usuario_modifica] [varchar](15) NULL,
	[fecha_modificacion] [datetime] NULL,
)
GO
ALTER TABLE AFI ADD CONSTRAINT AFINumeroIdentificacionEstado PRIMARY KEY CLUSTERED (TipoId ASC, NumeroIdentificacion ASC)


