/*Maestro de Archivos*/
IF OBJECT_ID('ARC','U') IS NOT NULL DROP TABLE ARC
GO
CREATE TABLE dbo.ARC(
	ARCHIVOID VARCHAR(20) NOT NULL DEFAULT REPLACE(RIGHT(NEWID(),20),'-',''),
	FORMULARIOID VARCHAR(20) NOT NULL,
	TIPOID VARCHAR(2) NOT NULL,
	NUMEROIDENTIFICACION VARCHAR(16) NOT NULL,
	FECHAREGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHARADICACION DATETIME DEFAULT NULL,
    MUNICIPIOID VARCHAR(10) NOT NULL,
    USUARIOID VARCHAR(100) NOT NULL,
    SEDEID VARCHAR(100) NOT NULL,
    NUEVOREGISTRO BIT DEFAULT 0,
    CANTIDADBENEFICIARIOS SMALLINT DEFAULT 0,
    SERIALSTICKER VARCHAR(20) DEFAULT NULL,
    ASESORID VARCHAR(15) NOT NULL
) 
GO
ALTER TABLE dbo.ARC ADD CONSTRAINT ARCARCHIVOID PRIMARY KEY CLUSTERED (ARCHIVOID ASC)
GO
ALTER TABLE dbo.ARC ADD CONSTRAINT ARCTIDTIPOID FOREIGN KEY (TIPOID) REFERENCES TID(TipoId)
GO
ALTER TABLE dbo.ARC ADD CONSTRAINT ARCMUNMUNICIPIOID FOREIGN KEY (MUNICIPIOID) REFERENCES MUN(MunicipioID)
GO
ALTER TABLE dbo.ARC ADD CONSTRAINT ARCUSUUSUARIOID FOREIGN KEY (USUARIOID,SEDEID) REFERENCES USU(USUARIOID,SEDEID)
GO
ALTER TABLE dbo.ARC ADD CONSTRAINT ARCASESORID FOREIGN KEY (ASESORID) REFERENCES ASE(ASESORID)