/*Maestro de Archivos*/
IF OBJECT_ID('ARCH','U') IS NOT NULL DROP TABLE ARCH
GO
CREATE TABLE dbo.ARCH(
	ARCHIVOID VARCHAR(20) NOT NULL DEFAULT REPLACE(RIGHT(NEWID(),20),'-',''),
	NOMBRE VARCHAR(MAX) NOT NULL,
	ARCHIVO VARBINARY(MAX) NOT NULL
) 
GO
ALTER TABLE dbo.ARCH ADD CONSTRAINT ARCHARCHIVOID PRIMARY KEY CLUSTERED (ARCHIVOID ASC)