/*Empresa*/
IF OBJECT_ID('EMP','U') IS NOT NULL DROP TABLE EMP
GO
CREATE TABLE EMP(
	EMPRESAID VARCHAR(100) NOT NULL
	,RAZONSOCIAL VARCHAR(500) NOT NULL
	,DOMICILIO VARCHAR(500) DEFAULT NULL
	,TELEFONO VARCHAR(20) DEFAULT NULL
	,NIT VARCHAR(20) DEFAULT NULL
	,ACTIVA SMALLINT DEFAULT 1
)
GO
ALTER TABLE EMP ADD CONSTRAINT [EMPRESAID] PRIMARY KEY CLUSTERED (EMPRESAID ASC)