/*Reportes*/
IF OBJECT_ID('REP','U') IS NOT NULL DROP TABLE REP
GO
CREATE TABLE REP(
	REPORTEID BIGINT NOT NULL IDENTITY(1,1)
	,NOMBRE VARCHAR(500) NOT NULL
	,QUERY VARCHAR(MAX) NOT NULL
)
GO
ALTER TABLE REP ADD CONSTRAINT REPREPORTEID PRIMARY KEY CLUSTERED (REPORTEID ASC)

