/*Permisos de Reportes por Usuario*/
IF OBJECT_ID('REPU','U') IS NOT NULL DROP TABLE REPU
GO
CREATE TABLE REPU(
	REPORTEID BIGINT NOT NULL
	,SEDEID VARCHAR(100) NOT NULL
	,USUARIOID VARCHAR(100) NOT NULL
)
GO
ALTER TABLE REPU ADD CONSTRAINT REPUREPORTEIDSEDEIDUSUARIOID PRIMARY KEY CLUSTERED (REPORTEID ASC, SEDEID ASC, USUARIOID ASC)
GO
ALTER TABLE REPU ADD CONSTRAINT REPUSEDEIDUSUARIOID_USUUSUARIOIDSEDEID FOREIGN KEY (USUARIOID,SEDEID) REFERENCES USU(USUARIOID,SEDEID)
