/*Sedes*/
IF OBJECT_ID('SED','U') IS NOT NULL DROP TABLE SED
GO
CREATE TABLE SED(
	SEDEID VARCHAR(100) NOT NULL
	,RAZONSOCIAL VARCHAR(500) NOT NULL
	,DOMICILIO	VARCHAR(500) NOT NULL
	,ACTIVA SMALLINT DEFAULT 1
	,TELEFONO VARCHAR(20) DEFAULT NULL
	,EMPRESAID VARCHAR(100) NOT NULL
)
GO
ALTER TABLE SED ADD CONSTRAINT SEDEID PRIMARY KEY CLUSTERED (SEDEID ASC)
GO
ALTER TABLE SED ADD CONSTRAINT SEDEMPRESAID_EMPEMPRESAID FOREIGN KEY (EMPRESAID) REFERENCES EMP(EMPRESAID)
