IF OBJECT_ID('TGEN','U') IS NOT NULL DROP TABLE TGEN
GO
CREATE TABLE [dbo].[TGEN](
	[TABLA] [varchar](15) NOT NULL,
	[CAMPO] [varchar](20) NOT NULL,
	[CODIGO] [varchar](20) NOT NULL,
	[DESCRIPCION] [varchar](256) NULL,
	[VALOR1] [decimal](14, 2) NULL,
	[DATO1] [varchar](255) NULL,
	[DFECHA] [tinyint] NULL,
	[OPCIONESLIBRES] [tinyint] NULL,
	[VALORINI] [decimal](14, 2) NULL,
	[VALORFIN] [decimal](14, 2) NULL,
	[VALOR2] [decimal](14, 2) NULL,
	[DATO2] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TGEN] 
ADD CONSTRAINT TGENTABLACAMPOCODIGO 
PRIMARY KEY CLUSTERED([TABLA] ASC,
	[CAMPO] ASC,
	[CODIGO] ASC)