/*Variables Generales del Sistema*/
IF OBJECT_ID('VSI','U') IS NOT NULL DROP TABLE VSI
GO
CREATE TABLE VSI(
	VARIABLEID VARCHAR(100) NOT NULL
	,DATO VARCHAR(MAX) NOT NULL
	,DENOMINACION VARCHAR(500) NOT NULL
)
GO
ALTER TABLE VSI ADD CONSTRAINT VSIVARIABLEID PRIMARY KEY CLUSTERED (VARIABLEID ASC)
GO
INSERT INTO VSI(VARIABLEID,DATO,DENOMINACION)VALUES('KEYCIFRAR','sCr1pTf0rM5','Llave para cifrar y descifrar claves de usuarios')
