IF OBJECT_ID (N'dbo.FNS_VALORVARIABLE', N'FN') IS NOT NULL DROP FUNCTION dbo.FNS_VALORVARIABLE;
GO
CREATE FUNCTION dbo.FNS_VALORVARIABLE (@VARIABLEID VARCHAR(100))
RETURNS VARCHAR(100)
WITH EXECUTE AS CALLER
AS
BEGIN
	DECLARE @DATO AS VARCHAR(100)

	SELECT @DATO = DATO FROM VSI WHERE VARIABLEID=@VARIABLEID

	RETURN @DATO
END;
GO