IF OBJECT_ID (N'dbo.FNS_QUERY_REP', N'FN') IS NOT NULL DROP FUNCTION dbo.FNS_QUERY_REP;
GO
CREATE FUNCTION dbo.FNS_QUERY_REP (@REPORTEID BIGINT)
RETURNS VARCHAR(MAX)
WITH EXECUTE AS CALLER
AS
BEGIN
	DECLARE @SQLString AS VARCHAR(MAX)
	DECLARE @NOMBRE VARCHAR(100)
	DECLARE @VALOR VARCHAR(MAX)

	SELECT @SQLString = QUERY FROM REP WHERE REPORTEID=@REPORTEID

	--SELECT NOMBRE,VALOR FROM REPP
	--SELECT QUERY FROM REP
	--AFI
	DECLARE _CURSOR CURSOR FOR   
		SELECT NOMBRE,VALOR FROM REPP WHERE REPORTEID=@REPORTEID 
    OPEN _CURSOR  
    FETCH NEXT FROM _CURSOR INTO @NOMBRE,@VALOR  

    --IF @@FETCH_STATUS <> 0   
        --PRINT '         <<None>>'       

    WHILE @@FETCH_STATUS = 0  
    BEGIN  
		
		SET  @SQLString=REPLACE(@SQLString,@NOMBRE,''''+@VALOR+'''')
        --PRINT @message  
        FETCH NEXT FROM _CURSOR INTO @NOMBRE,@VALOR  
        END  

    CLOSE _CURSOR  
    DEALLOCATE _CURSOR


	RETURN @SQLString
END;
GO
SELECT dbo.FNS_QUERY_REP(1)
--SELECT top 1000 * FROM [ScriptForms].[dbo].[AFI] WHERE ISNULL(TipoId,'') = CASE WHEN ISNULL('RC','')<>'' THEN 'RC' ELSE TipoId END