IF OBJECT_ID (N'dbo.FNS_FECHA_CADENA', N'FN') IS NOT NULL DROP FUNCTION dbo.FNS_FECHA_CADENA;
GO
CREATE FUNCTION dbo.FNS_FECHA_CADENA (@FECHA DATETIME)
RETURNS VARCHAR(20)
WITH EXECUTE AS CALLER
AS
BEGIN
	RETURN CONVERT(VARCHAR,@FECHA,103)+' '+CONVERT(VARCHAR,@FECHA,108)
END;
GO
PRINT DBO.FNS_FECHA_CADENA(GETDATE());